In [2]:
import torch
import torchvision
import numpy as np

In [2]:
print(torch.__version__)

1.4.0


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda


'10.1'

In [5]:
dd=[[1,2,3],[4,6,2],[5,1,0]]

In [6]:
dd = torch.tensor(dd)

In [7]:
dd.shape


torch.Size([3, 3])

In [8]:
dd.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [6],
        [2],
        [5],
        [1],
        [0]])

In [9]:
dd.reshape(3,3).shape


torch.Size([3, 3])

In [10]:
len(dd)

3

In [11]:
t=torch.Tensor()
t.dtype

torch.float32

In [12]:
# 3 attributes or Pytorrch tensor: dtype, device, layout
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [13]:
t=t.cuda()
print(t.device)

cuda:0


In [14]:
d =torch.tensor([1,2],dtype = torch.int)
e =torch.tensor([2,3],dtype = torch.float32)
f = d + e
print(f.dtype)

torch.float32


In [15]:
#creating tensors without data
t=torch.eye(2)
print(t)
x=torch.zeros((3,2))
print(x)
x=torch.ones((3,2))
print(x)
x=torch.rand((3,2))
print(x)


tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0.1818, 0.0138],
        [0.2945, 0.9986],
        [0.8232, 0.3540]])


In [16]:
# creating tensor with data 
data = np.array([3,4,5])
print(data.dtype)
type(data) 

o1= torch.Tensor(data)
o2= torch.tensor(data)
o3= torch.as_tensor(data)
o4= torch.from_numpy(data)

print(o1)
print(o2)
print(o3)
print(o4)
# the first one is a constructor function while the other 3 are factory functions. Factory functions are the functions to create the 
# object of the class just like constructor but they have various other features to infer the data
# That's why the torch.Tensor() gives the output with  default data type while all the other factory functions
# infer the incoming data to be of int32 type and hence make the output of int32 type
torch.get_default_dtype()   #this is the default data type of pytorch
# factory functions also allow to set the data type explicitly
a= torch.tensor(np.array([1,2,3]))
b = torch.tensor(np.array([1.,2.,3.]))
c =torch.tensor(np.array([1,2,3]),dtype= torch.float64)
print(a,b,c)

int32
tensor([3., 4., 5.])
tensor([3, 4, 5], dtype=torch.int32)
tensor([3, 4, 5], dtype=torch.int32)
tensor([3, 4, 5], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32) tensor([1., 2., 3.], dtype=torch.float64) tensor([1., 2., 3.], dtype=torch.float64)


In [17]:
#Memory: Sharing vs Copying
data[0]=5
data[1]=5
data[2]=5
print(o1)
print(o2)
print(o3)
print(o4)
# changing the numpy array changed the tensor for the torch.as_tensor() and torch.from_numpy() because they share the memory while 
# there was no change in torch.tensor() and torch.Tensor() as they create a new copy

tensor([3., 4., 5.])
tensor([3, 4, 5], dtype=torch.int32)
tensor([5, 5, 5], dtype=torch.int32)
tensor([5, 5, 5], dtype=torch.int32)


In [18]:
# Essential tensor Operations

t = torch.tensor([[2,3,2,4],[5,6,6,7],[8,9,1,0]],dtype=torch.float64)
print(t)


tensor([[2., 3., 2., 4.],
        [5., 6., 6., 7.],
        [8., 9., 1., 0.]], dtype=torch.float64)


In [19]:
t.size()


torch.Size([3, 4])

t.shape


In [20]:
len(t.shape)  #rank of the tensor


2

In [21]:
torch.tensor(t.shape).prod()


tensor(12)

In [22]:
t.numel()   #tells the number of elements

12

In [23]:
t.reshape((1,12))

tensor([[2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.]], dtype=torch.float64)

In [24]:
t.reshape((4,3)) # point to notice is reshaping (3,4) to (4,3) doesn't takes the transpose rather it just re-arranges the numbers
                 # starting from index 1 

tensor([[2., 3., 2.],
        [4., 5., 6.],
        [6., 7., 8.],
        [9., 1., 0.]], dtype=torch.float64)

In [25]:
t.reshape((4,1,3))

tensor([[[2., 3., 2.]],

        [[4., 5., 6.]],

        [[6., 7., 8.]],

        [[9., 1., 0.]]], dtype=torch.float64)

In [26]:
t.reshape((3,2,2))

tensor([[[2., 3.],
         [2., 4.]],

        [[5., 6.],
         [6., 7.]],

        [[8., 9.],
         [1., 0.]]], dtype=torch.float64)

In [27]:
t.reshape((2,3,2)).shape

torch.Size([2, 3, 2])

In [28]:
#reshape can change the rank   if there are 3 numbers mentioned in reshape, its basically 2 dimension
#(3,4)--> (2,3,2) means 2 elements and each element is in  (3,2) shape. So the rank becomes 3,
#but the numberof elements never change
t=t.reshape((2,3,2))
print(t)
print(t.shape)



tensor([[[2., 3.],
         [2., 4.],
         [5., 6.]],

        [[6., 7.],
         [8., 9.],
         [1., 0.]]], dtype=torch.float64)
torch.Size([2, 3, 2])


In [29]:
# squeeze and unsqueeze only work if one of the dimension is 1 
# squeeze and unsqueeze can change the rank by taking away or adding one rank if one of the dimension is 1
q=t.reshape((12,1)).squeeze()
print(q)
print(q.shape)
p=q.unsqueeze(dim=0)
print(p)
print(p.shape)


tensor([2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.], dtype=torch.float64)
torch.Size([12])
tensor([[2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.]], dtype=torch.float64)
torch.Size([1, 12])


In [30]:
# flatten function just creates a vector by concatinating all the existing dimension in a single row
#flatten basically reshapes and squeeze together
print(q.reshape((2,2,3)))
print(q.flatten())
print(q.shape)

tensor([[[2., 3., 2.],
         [4., 5., 6.]],

        [[6., 7., 8.],
         [9., 1., 0.]]], dtype=torch.float64)
tensor([2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.], dtype=torch.float64)
torch.Size([12])


In [31]:
#by using -1 we can use reshape to do what flatten does
print(q.reshape((2,2,3)))
print(torch.reshape(q,(-1,)))
print(q.shape)

tensor([[[2., 3., 2.],
         [4., 5., 6.]],

        [[6., 7., 8.],
         [9., 1., 0.]]], dtype=torch.float64)
tensor([2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.], dtype=torch.float64)
torch.Size([12])


In [32]:
#my own flatten function 
def flat(a):
    a=a.reshape((1,-1))
    print(a.shape)
    a=a.squeeze()
    return a
print(t.shape)
s=flat(t)
print(s)

torch.Size([2, 3, 2])
torch.Size([1, 12])
tensor([2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.], dtype=torch.float64)


In [33]:
#different axes alomg which we can flatten the tensor
t=t.reshape((4,3,1))
print(t)
q=t.flatten()
p=t.flatten(start_dim=1)
print(q,q.shape)
print(p)
print(p.shape)
s=t.flatten(end_dim=1)
print(s,s.shape)

tensor([[[2.],
         [3.],
         [2.]],

        [[4.],
         [5.],
         [6.]],

        [[6.],
         [7.],
         [8.]],

        [[9.],
         [1.],
         [0.]]], dtype=torch.float64)
tensor([2., 3., 2., 4., 5., 6., 6., 7., 8., 9., 1., 0.], dtype=torch.float64) torch.Size([12])
tensor([[2., 3., 2.],
        [4., 5., 6.],
        [6., 7., 8.],
        [9., 1., 0.]], dtype=torch.float64)
torch.Size([4, 3])
tensor([[2.],
        [3.],
        [2.],
        [4.],
        [5.],
        [6.],
        [6.],
        [7.],
        [8.],
        [9.],
        [1.],
        [0.]], dtype=torch.float64) torch.Size([12, 1])


In [34]:
#concatenating is merging elements along existing axes with no change in rank 
#stacking is merging tensors as elements of a new axesy, hence stacking changes the rank
#stacking is used to create batch
t1=torch.tensor([[1,2,3],[3,4,5]])
t2=torch.tensor([[6,3,4],[3,4,8]])
t3=torch.cat((t1,t2),dim=0)
t4=torch.cat((t1,t2),dim=1)
print(t1,'\n',t2,'\n',t3,'\n',t4,'\n',t3.shape,'\n',t4.shape)
t5=torch.stack((t1,t2))
print(t5,'n',t5.shape)

tensor([[1, 2, 3],
        [3, 4, 5]]) 
 tensor([[6, 3, 4],
        [3, 4, 8]]) 
 tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 3, 4],
        [3, 4, 8]]) 
 tensor([[1, 2, 3, 6, 3, 4],
        [3, 4, 5, 3, 4, 8]]) 
 torch.Size([4, 3]) 
 torch.Size([2, 6])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[6, 3, 4],
         [3, 4, 8]]]) n torch.Size([2, 2, 3])


In [35]:
#Element wise access operation 
a= torch.tensor([[1,2,3],[4,5,6]])
b= torch.tensor([[0,5,4],[4,8,3]])
c= torch.tensor([[5,2,6],[6,3,9]])
print(a.shape,b.shape,c.shape)
tens= torch.stack((a,b,c))
print(tens.shape)
tens= tens.reshape([3,1,2,3])
print(tens.shape)
# this is like concatenating 3: 2x3 images with one color channel 
print(tens[0])   #first image of the batch
print(tens[0][0]) #first channel of first image of the batch
print(tens[0][0][0]) #first row of the first channel of first image of the batch
print(tens[0][0][0][0]) #first pixel value of the first row of the first channel of first image of the batch

torch.Size([2, 3]) torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 1, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor(1)


In [36]:
#ways to flatten tensor
print(tens.flatten())
print(tens.reshape(1,-1)[0])
print(tens.reshape(-1))
print(tens.view(tens.numel()))

tensor([1, 2, 3, 4, 5, 6, 0, 5, 4, 4, 8, 3, 5, 2, 6, 6, 3, 9])
tensor([1, 2, 3, 4, 5, 6, 0, 5, 4, 4, 8, 3, 5, 2, 6, 6, 3, 9])
tensor([1, 2, 3, 4, 5, 6, 0, 5, 4, 4, 8, 3, 5, 2, 6, 6, 3, 9])
tensor([1, 2, 3, 4, 5, 6, 0, 5, 4, 4, 8, 3, 5, 2, 6, 6, 3, 9])


In [37]:
print(tens.flatten(start_dim=1))
print(tens.flatten(start_dim=1).shape)

tensor([[1, 2, 3, 4, 5, 6],
        [0, 5, 4, 4, 8, 3],
        [5, 2, 6, 6, 3, 9]])
torch.Size([3, 6])


In [38]:
# another way to flatten only desired dimension using reshape instead of flatten
print(tens.reshape(tens.shape[0],-1))
print(tens.reshape(tens.shape[0],-1).shape)

tensor([[1, 2, 3, 4, 5, 6],
        [0, 5, 4, 4, 8, 3],
        [5, 2, 6, 6, 3, 9]])
torch.Size([3, 6])


## ELEMENT WISE OPERATIONS

In [3]:
t1 = torch.tensor([[1,2],[3,4]],dtype = torch.float32)
t2 = torch.tensor([[5,0],[6,8]],dtype = torch.float32)

In [4]:
#for any kind of elemnt wise operation we need the 2 tensors to be of the same size
t1 = t1 +t2
print(t1)

tensor([[ 6.,  2.],
        [ 9., 12.]])


##Tensor Broadcasting 

In [6]:
# Broadcasting in case of scalar even if scalar's shape doesn't match with the tensor
print(t1 + 2)
print(t1.add(2))
print(t1 * 2)
print(t1.mul(2))
print(t1/2)
print(t1.div(2))
print(t1 - 2)
print(t1.sub(2))

tensor([[ 8.,  4.],
        [11., 14.]])
tensor([[ 8.,  4.],
        [11., 14.]])
tensor([[12.,  4.],
        [18., 24.]])
tensor([[12.,  4.],
        [18., 24.]])
tensor([[3.0000, 1.0000],
        [4.5000, 6.0000]])
tensor([[3.0000, 1.0000],
        [4.5000, 6.0000]])
tensor([[ 4.,  0.],
        [ 7., 10.]])
tensor([[ 4.,  0.],
        [ 7., 10.]])


In [12]:
t2 = np.broadcast_to(2,t1.shape)
print(t2)

[[2 2]
 [2 2]]


In [13]:
k =t1+2
print(k)

tensor([[14., 10.],
        [17., 20.]])


In [16]:
k2 = t1 + torch.tensor(np.broadcast_to(2,t1.shape),dtype=torch.float32)
print(k2,'\n',t1)

tensor([[14., 10.],
        [17., 20.]]) 
 tensor([[12.,  8.],
        [15., 18.]])


In [17]:
a1 = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
a2 = torch.tensor([1,2],dtype=torch.float32)

a3 = a1+a2
print(a3)
print(np.broadcast_to(a2.numpy(),a1.shape))

tensor([[2., 4.],
        [4., 6.]])


In [18]:
# Broadcasting has multiple other applications but the basic requirement arise for the element-wise 
# operation which requires the two tensors to be of same shape

[[1. 2.]
 [1. 2.]]


In [20]:
#element-wise Comparision Operation
t1 = torch.tensor([[1,2,4],[4,5,6]],dtype= torch.float32)
print(t1.eq(5))
print(t1.gt(2))
print(t1.ge(3))
print(t1.lt(6))
print(t1.le(12))

tensor([[False, False, False],
        [False,  True, False]])
tensor([[False, False,  True],
        [ True,  True,  True]])
tensor([[False, False,  True],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[True, True, True],
        [True, True, True]])


In [21]:
# Element wise function application
t1 =torch.tensor([[2,3,4],[3,-4,1]], dtype = torch.float32)
print(t1.sqrt())
print(t1.abs())
print(t1.neg())
print(t1.mean()) # not an element wise operation

tensor([[1.4142, 1.7321, 2.0000],
        [1.7321,    nan, 1.0000]])
tensor([[2., 3., 4.],
        [3., 4., 1.]])
tensor([[-2., -3., -4.],
        [-3.,  4., -1.]])
tensor(1.5000)


In [23]:
# Arg Max and Reduction Tensor Operation
# Reduction Operation is an operation which when performed on a tensor reduces the number of 
# elements contained in the tensor. Or its a way to perform the operation among the elements 
# of the tensor
t = torch.tensor([[1,3,4],[3,5,2],[3,7,3]],dtype = torch.float32)
print(t.sum())
print(t.numel())
print(t.sum().numel())
print(t.sum().numel()<t.numel())
print(t.prod())
print(t.std())
print(t.mean())

tensor(31.)
9
1
True
tensor(22680.)
tensor(1.7401)
tensor(3.4444)


In [26]:
t = torch.tensor([[1,1,1,1],[2,2,2,2],[3,3,3,3]],dtype = torch.float32)
print(t.sum(dim=0))
print(t[0] + t[1] +t[2])
print(t.sum(dim=1))
print(t[0].sum() , t[1].sum() , t[2].sum())

tensor([6., 6., 6., 6.])
tensor([6., 6., 6., 6.])
tensor([ 4.,  8., 12.])
tensor(4.) tensor(8.) tensor(12.)


In [27]:
t = torch.tensor([[3,5,0,2],[23,46,35,4],[2,8,2,6]],dtype=torch.float32)
print(t.max())
print(t.argmax())
print(t.flatten().argmax())

tensor(46.)
tensor(5)
tensor(5)


In [29]:
#watch it carefully to understand; for a 3x4 vector 
#dim0 will have 4 elements, dim1 will have 3 elements after the reduction operation 
print(t.max(dim=0))
print(t.max(dim=1))

torch.return_types.max(
values=tensor([23., 46., 35.,  6.]),
indices=tensor([1, 1, 1, 2]))
torch.return_types.max(
values=tensor([ 5., 46.,  8.]),
indices=tensor([1, 1, 1]))


In [32]:
#dim0 will have 2-3x4 elements,after the reduction operation 
#dim1 will have 3-2x4 elements,after the reduction operation 
#dim0 will have 4-2x3 elements,after the reduction operation 
t = torch.tensor([[[3,5,0,2],[23,46,35,4],[29,8,23,6]],[[31,5,70,2],[20,6,32,40],[25,18,12,65]]],dtype=torch.float32)
print(t)
print(t.shape)
print(t.max(dim=0))
print(t.argmax(dim=0))
print(t.max(dim=1))
print(t.argmax(dim=1))
print(t.max(dim=2))
print(t.argmax(dim=2))

tensor([[[ 3.,  5.,  0.,  2.],
         [23., 46., 35.,  4.],
         [29.,  8., 23.,  6.]],

        [[31.,  5., 70.,  2.],
         [20.,  6., 32., 40.],
         [25., 18., 12., 65.]]])
torch.Size([2, 3, 4])
torch.return_types.max(
values=tensor([[31.,  5., 70.,  2.],
        [23., 46., 35., 40.],
        [29., 18., 23., 65.]]),
indices=tensor([[1, 1, 1, 1],
        [0, 0, 0, 1],
        [0, 1, 0, 1]]))
tensor([[1, 1, 1, 1],
        [0, 0, 0, 1],
        [0, 1, 0, 1]])
torch.return_types.max(
values=tensor([[29., 46., 35.,  6.],
        [31., 18., 70., 65.]]),
indices=tensor([[2, 1, 1, 2],
        [0, 2, 0, 2]]))
tensor([[2, 1, 1, 2],
        [0, 2, 0, 2]])
torch.return_types.max(
values=tensor([[ 5., 46., 29.],
        [70., 40., 65.]]),
indices=tensor([[1, 1, 0],
        [2, 3, 3]]))
tensor([[1, 1, 0],
        [2, 3, 3]])


In [38]:
#accessing elements of tensor
print(t.shape)
print(t.mean())
print(t.mean().item())
print(t.mean(dim=0).tolist())
print(t.mean(dim=1).numpy())

torch.Size([2, 3, 4])
tensor(21.2500)
21.25
[[17.0, 5.0, 35.0, 2.0], [21.5, 26.0, 33.5, 22.0], [27.0, 13.0, 17.5, 35.5]]
[[18.333334 19.666666 19.333334  4.      ]
 [25.333334  9.666667 38.       35.666668]]
