In [1]:
import torch 

In [3]:
# Generating random data 
torch.manual_seed(8)  # fixing the random data for every run 
features = torch.randn((1,5))  # generating a 1x5 tensor containing random values from normal distribution
weights = torch.randn_like(features) # function randn_like produces tensor of same shape as the input variable
bias =torch.randn((1,1))

In [4]:
# Exercise to design and calculate the output of the neural networks using above weight and features
#features = features.flatten()
#weights =  weights.flatten()
h =  torch.sum(features*weights) + bias
out = sigmoid_activation(h)
print(out)

# Now using mattrix multiplication # torch.mamul supports broadcasting hence may give spurious output in manual error in shape assignment
features = features.view(5,1)
h = torch.mm(weights, features) +bias  #matrices size should be in agreement
out = sigmoid_activation(h)

tensor([[0.0803]])


In [2]:
def nn(weights,features,bias):
    out= sigmoid_activation(torch.mm(weights,features) + bias)
    return out

In [3]:
def sigmoid_activation(x):
    return 1/(1+torch.exp(-x))   # torch.exp is the tensor version of exp function which imput and output elements of tensor type 

In [6]:
# multi-layer neural net
torch.manual_seed(10)
features= torch.randn((1,3))

#defining the size of each layer
n_input= features.shape[1]
n_hidden= 2
n_out= 1

#defining weights
weights1 = torch.randn((n_hidden,n_input))
weights2 = torch.randn((n_out,n_hidden))

bias1= torch.randn((1,n_hidden))
bias2= torch.randn((1,n_out))

# forward pass using torch.mm
out1= nn(weights1,features.T,bias1.T)
out2= nn(weights2,out1,bias2.T)
print (out1,out2)

tensor([[0.2821],
        [0.9840]]) tensor([[0.7264]])


In [9]:
# Bridging torch and numpy
import numpy as np
import torch

a= np.random.rand(5,4)
b= torch.from_numpy(a)
print(a,b)
b.mul_(2)
print(a,b)
print(b.numpy())

[[0.42735335 0.92197733 0.98238046 0.13069527]
 [0.95221278 0.18855762 0.75948477 0.71073285]
 [0.62116921 0.06093111 0.54930865 0.13491466]
 [0.57545678 0.56869089 0.61090347 0.2128043 ]
 [0.60265387 0.62150924 0.70164005 0.49983654]] tensor([[0.4274, 0.9220, 0.9824, 0.1307],
        [0.9522, 0.1886, 0.7595, 0.7107],
        [0.6212, 0.0609, 0.5493, 0.1349],
        [0.5755, 0.5687, 0.6109, 0.2128],
        [0.6027, 0.6215, 0.7016, 0.4998]], dtype=torch.float64)
[[0.85470669 1.84395467 1.96476092 0.26139054]
 [1.90442556 0.37711524 1.51896955 1.42146571]
 [1.24233841 0.12186222 1.09861731 0.26982931]
 [1.15091356 1.13738178 1.22180695 0.42560861]
 [1.20530773 1.24301849 1.40328009 0.99967309]] tensor([[0.8547, 1.8440, 1.9648, 0.2614],
        [1.9044, 0.3771, 1.5190, 1.4215],
        [1.2423, 0.1219, 1.0986, 0.2698],
        [1.1509, 1.1374, 1.2218, 0.4256],
        [1.2053, 1.2430, 1.4033, 0.9997]], dtype=torch.float64)
[[0.85470669 1.84395467 1.96476092 0.26139054]
 [1.90442556 0.37